### ISSUE TITLE
图书馆预约服务无法使用

### ISSUE THREAD

**Issue by shepard-liu** [orangeboyChen/whu-ham#1]
感谢大佬开发这个APP，课表功能真的好用

版本：1.0 Beta-8

<img width="274" alt="Snipaste_2021-12-02_17-54-40" src="https://user-images.githubusercontent.com/59480032/144399367-9190727f-9a82-4563-adcb-39185d2d5772.png">

填入信息后，显示登陆超时。

**Comment by orangeboyChen** [comment]
> 感谢大佬开发这个APP，课表功能真的好用
> 
> 版本：1.0 Beta-8
> 
> <img alt="Snipaste_2021-12-02_17-54-40" width="274" src="https://user-images.githubusercontent.com/59480032/144399367-9190727f-9a82-4563-adcb-39185d2d5772.png">
> 
> 填入信息后，显示登陆超时。

现在看起来图书馆的服务器宕了，图书馆网站、小程序都进不去

**Comment by shepard-liu** [comment]
确实如此...
另外大佬有开源计划吗，我觉得这个APP可以发展成为一个校园服务平台
我相信很多开发者都愿意去贡献代码的

**Comment by orangeboyChen** [comment]
其实我非常想开源的。。但app中有很多我个人的配置信息，包括安卓的推送服务和苹果的开发者账号等等，所以为了安全就暂不开源了
以后等到这些个人配置信息和项目解耦了，应该就可以开源了

**Comment by shepard-liu** [comment]
好的，期待这一天的到来。

**Comment by orangeboyChen** [comment]
目前图书馆服务已恢复
