### ISSUE TITLE
安卓状态页面显示bug

### ISSUE THREAD

**Issue by minnakamiyuki** [orangeboyChen/whu-ham#16]
![Screenshot_20220304_192932_com nowcent ham_edit_38976451486239](https://user-images.githubusercontent.com/84240546/156756025-6a85fdcf-c74f-4a72-b1c1-f35188b7ece1.jpg)
如图所示

**Comment by minnakamiyuki** [comment]
![Screenshot_20220304_193250_com nowcent ham_edit_39048450443520](https://user-images.githubusercontent.com/84240546/156756181-0f6f00b2-e63c-414e-9550-0105f94f4893.jpg)

**Comment by orangeboyChen** [comment]
😄 感谢，我抽空处理下
