### ISSUE TITLE
关于12.4安卓安装包解析问题

### ISSUE THREAD

**Issue by wawjswt** [orangeboyChen/whu-ham#20]
学长好，最新的12.4版本安装包解析总是出现错误，无法安装

**Comment by orangeboyChen** [comment]
目前还不清楚是什么问题（捂脸
请问重新安装也不可以吗

**Comment by wawjswt** [comment]
> 

是的，删掉了旧版本安装也不行。是不是打包的时候出现了什么问题

**Comment by orangeboyChen** [comment]
🉑️我找个时间看看
我先把另一个包放出来吧，感谢

**Comment by orangeboyChen** [comment]
更新至1.2.5了，可以再试一试（？）

**Comment by orangeboyChen** [comment]
破案了，1.2.4上传的过程出现了问题，十分感谢🙏
