### ISSUE TITLE
安卓暗色模式下字体颜色问题

### ISSUE THREAD

**Issue by jonnygood** [orangeboyChen/whu-ham#25]
部分字体在暗色模式下仍呈现黑色
![Uploading Screenshot_20221118_190046_com.nowcent.ham_edit_2331672452343689.jpg…]()
![Uploading Screenshot_20221118_190049_com.nowcent.ham.jpg…]()

**Comment by orangeboyChen** [comment]
get☑️

**Comment by orangeboyChen** [comment]
过了这么久，这个页面已经重构了，应该解决了～
