### ISSUE TITLE
图书馆预约闪退

### ISSUE THREAD

**Issue by HonghaoQiu** [orangeboyChen/whu-ham#32]
闪退后软件打开就闪退

**Comment by orangeboyChen** [comment]
Android还是iOS呢

**Comment by HonghaoQiu** [comment]
安卓



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月13日(周四) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [orangeboyChen/whu-ham] 图书馆预约闪退 (Issue #32)




 
Android还是iOS呢

**Comment by xiwen1** [comment]
安卓可以通过设置里的首选座位预约不会闪退，但是直接预约的时候就会在查询座位信息的时候闪退

**Comment by orangeboyChen** [comment]
嗯，我看到日志了，我分析下哈

**Comment by orangeboyChen** [comment]
May fixed by v1.4.2
