### ISSUE TITLE
图书馆预约系统问题

### ISSUE THREAD

**Issue by Andytonglove** [orangeboyChen/whu-ham#33]
或许是图书馆登录系统更新造成

**Comment by orangeboyChen** [comment]
发现了，请问智慧珞珈里可以打开吗

**Comment by Andytonglove** [comment]
> 发现了，请问智慧珞珈里可以打开吗

智慧珞珈也不可以，应该是app的api无了

**Comment by orangeboyChen** [comment]
感觉不太可能，图书馆公告也没有改，应该是外包的系统出问题了

**Comment by orangeboyChen** [comment]
我这边把app的问题反馈给学校了，看看怎么处理吧

**Comment by Andytonglove** [comment]
> 我这边把app的问题反馈给学校了，看看怎么处理吧

谢谢老哥！

**Comment by Andytonglove** [comment]
> > > 我这边把app的问题反馈给学校了，看看怎么处理吧
> > 
> > 谢谢老哥！
> 
> 智慧珞珈里也是提示，登陆出错了请重试吗

![Screenshot_20231017_142117.jpg](https://github.com/orangeboyChen/whu-ham/assets/74820970/b1c9de83-f58d-46f5-9a62-0b1c8cb3d380)

**Comment by Andytonglove** [comment]
联系了之后图书馆给的回复是外包系统故障，说尽量在6点恢复
