### ISSUE TITLE
关于查得分数据界面分段的建议

### ISSUE THREAD

**Issue by xyz-whu-coder** [orangeboyChen/whu-ham#36]
可以按武大的分数-绩点分段来排（？可能可以让大家看得更清楚点）：

| 成绩          | 绩点 |
| :---           | :--- |
| 90－100   | 4.0 |
| 85－89    | 3.7 |
| 82－84    | 3.3 |
| 78－81    | 3.0 |
| 75－77    | 2.7 |
| 72－74    | 2.3 |
| 68－71    | 2.0 |
| 64－67    | 1.5 |
| 60－63    | 1.0 |
| 60分以下 | 0 |

因为似乎目前的版本只有85会单独划档（
![image](https://github.com/orangeboyChen/whu-ham/assets/116661413/29d8e4dc-95a8-4539-8ad2-b3b73ea626ea)

**Comment by orangeboyChen** [comment]
我感觉这样分段数太多了，反而不太直观。。但是后面按照绩点的分段配置了展示，可以再看下～
