### ISSUE TITLE
编辑课程信息后无法保存

### ISSUE THREAD

**Issue by chenxiex** [orangeboyChen/whu-ham#37]
![Screenshot_20240913_153331_com.nowcent.ham.jpg](https://github.com/user-attachments/assets/97d73915-32d8-41a5-875b-6f740c09b7b6)

如图，课程编辑页面没有保存按钮。只能先“重置这门课”，然后再次编辑才有保存按钮。但这已经是刚刚从教务系统获取的课程了，重置之后反而会导致上课时间改变，和教务系统不一致。

**Comment by chenxiex** [comment]
> 这里是一门课的编辑页，更改时间、节数会影响每周的课程。如果需要更改“某一节课”，可以试下长按课程直接拖动🤔

我就是要修改这一门课的信息。这门课的上课地址写在课程备注里，app无法正确获取到地址，因此我希望手动修改这门课的上课地点。但是修改地点前后这个页面都没有“保存”按钮，只有“重置这门课”。哪怕我从教务系统获取课程表之后什么都不修改，也只有“重置这门课”一个按钮。

**Comment by orangeboyChen** [comment]
看了下代码，貌似有个重置课程判断的bug，任何开始周、结束周不连续的课程都会有这个问题。感谢反馈，我找个时间修复下🙏

**Comment by orangeboyChen** [comment]
1.5.2 fix
