### ISSUE TITLE
源码里面的SlideToActView是作者自行开发的验证码加载ui吗

### ISSUE THREAD

**Issue by CarryHJR** [orangeboyChen/whu-ham#39]

**Comment by orangeboyChen** [comment]
https://github.com/cortinico/slidetoact 是这个吗？
远古版本有用到过，用在滑动解锁上（就是图书馆取消预约的那个操作）。后来页面全部重构，在全量转Compose后就没用了。
信息门户验证码加载的ui，本质上是一个html

**Comment by CarryHJR** [comment]
噢噢 再请教一下 在场馆预约里面，发起验证码拿到token后 发起GSOrder，如果没有空余场地失败后，这个token可以用来发起新的预订吗，还是说必须得创造新的验证码请求

**Comment by CarryHJR** [comment]
噢噢，感觉这个验证码的页面加载很有点耗时，感觉要0.5s左右，基本时间瓶颈就卡在加载这里了

**Comment by orangeboyChen** [comment]
其实有个办法，可以提前获取验证码token。因为验证码是第三方服务，按道理来说没有请求时间限制。

**Comment by CarryHJR** [comment]
应该可行 不过建议还是app里不加入这个功能了，给大伙留点手速比拼的空间

**Comment by orangeboyChen** [comment]
> 其实有个办法，可以提前获取验证码token。因为验证码是第三方服务，按道理来说没有请求时间限制。

其实“收藏预约”是支持提前刷验证码的。收藏预约不受系统预约时间限制，不过要提前选定好预约的场所
