### ISSUE TITLE
图书馆预约功能无法使用

### ISSUE THREAD

**Issue by NagisaCo** [orangeboyChen/whu-ham#4]
> - 平台：安卓
> - 系统版本：Android 11
> - 软件版本：1.0-beta9
> - 功能模块：图书馆登录

请问现在还能正常登录图书馆吗？我看其他 issue 好像可以正常登录，但是我这儿提示**手机app已停用**。

<img src="https://user-images.githubusercontent.com/25633151/144730837-9f322c59-88d5-42c2-a0c8-548e0ef7ef79.jpg" height = "400" alt="" align=center />

**Comment by orangeboyChen** [comment]
对的，今早app的接口改了，正在修复

**Comment by NagisaCo** [comment]
> 对的，今早app的接口改了，正在修复

好的，谢谢，辛苦了😁

**Comment by orangeboyChen** [comment]
已修复，感谢
