### ISSUE TITLE
导入课表链接成绩失败

### ISSUE THREAD

**Issue by Conmigo13** [orangeboyChen/whu-ham#40]
刚刚下载了1.5.2最新版，但是导入课表还是显示空白，并且链接成绩也出现问题，这是怎么回事呢![Screenshot_2024-10-28-16-59-11-152_com.nowcent.ham.jpg](https://github.com/user-attachments/assets/f1d7b4c1-1254-4cf5-9604-33be2b007c33)

![Screenshot_2024-10-28-16-55-07-589_com.nowcent.ham.jpg](https://github.com/user-attachments/assets/e037e112-0850-42d9-9368-7f2d7f35c462)

**Comment by orangeboyChen** [comment]
最近这两个的获取逻辑移植到了rn上，可能会有兼容问题，晚上我看一下

**Comment by orangeboyChen** [comment]
有点尴尬，之前因为做包瘦身把回退能力搞没了，可能要单独发包解决了

**Comment by Conmigo13** [comment]
> 有点尴尬，之前因为做包瘦身把回退能力搞没了，可能要单独发包解决了

加油加油

**Comment by Conmigo13** [comment]
> 有点尴尬，之前因为做包瘦身把回退能力搞没了，可能要单独发包解决了

加油加油

**Comment by orangeboyChen** [comment]
1.5.2.104应该fix了。如果升级后打开“成绩”闪退，记得清空课程表/清空app数据哈。100获取课程表后会导入致命错误的数据
