### ISSUE TITLE
预约座位显示是否有问题呢

### ISSUE THREAD

**Issue by Cakeyan** [orangeboyChen/whu-ham#6]
为什么约总馆A5好像不管什么座位显示的座位号都是505
![Screenshot_2021-12-08-13-46-50-626_com nowcent ham](https://user-images.githubusercontent.com/77425002/145155155-798475a4-a130-493d-8b48-ed1ec41509b1.jpg)

**Comment by orangeboyChen** [comment]
确实有问题哈
