### ISSUE TITLE
可否添加查给分功能呢

### ISSUE THREAD

**Issue by game-loader** [orangeboyChen/whu-ham#7]
如题，非常希望还能有这个功能

**Comment by orangeboyChen** [comment]
目前还是有这个计划的，但要添加查给分功能有几个问题待解决
- 上传成绩到服务器可能会牵涉到隐私问题，虽然可以采用**非必要不上传**和**知情同意后再上传**的方式，不过这个还待商榷
- 样本数量

**Comment by game-loader** [comment]
给充足的提醒用户同意属于自愿给出数据使用权应该不算隐私吧，样本的话有这个功能我们都可以帮忙宣传，让大家都用，数量就会充足起来

**Comment by orangeboyChen** [comment]
确实哈，在做了

**Comment by NagisaCo** [comment]
看到新增了查给分的功能，我这里在9月初爬了些梦想珈的数据，如果有需要的话可以直接使用

https://github.com/NagisaCo/CourseR/tree/main/Score%E8%AF%BE%E7%A8%8B%E7%BB%99%E5%88%86%E6%95%B0%E6%8D%AE

**Comment by orangeboyChen** [comment]
> 看到新增了查给分的功能，我这里在9月初爬了些梦想珈的数据，如果有需要的话可以直接使用
> 
> https://github.com/NagisaCo/CourseR/tree/main/Score%E8%AF%BE%E7%A8%8B%E7%BB%99%E5%88%86%E6%95%B0%E6%8D%AE

哈哈，感谢大佬，回去研究一下
